### ISSUE TITLE
v1.2.0_coreos.1 image has invalid signature

### ISSUE THREAD

**Issue by bharrisau** [coreos/coreos-kubernetes#363]
I've just tried deploying to AWS using `kube-aws` and the `v1.2.0_coreos.1` image. After waiting a while I logged in and found the `kubelet.service` was failing to start due to invalid signature from `openpgp`. Change the service file to use `v1.2.0_coreos.0` image and it signature verification worked.

Also tried deleting the cached `quay.io` public key, but the freshly downloaded one failed signature verification too.

Also note, this was with the beta release channel.

**Comment by colhom** [comment]
\cc @aaronlevy

**Comment by aaronlevy** [comment]
@bharrisau can you give it another try? There was an issue on our end with the image build, but should be resolved.

**Comment by pbx0** [comment]
This is odd -- I've successfully pulled this image yesterday and ran a cluster and conformance tests. This morning I spin up a new alpha machine and rkt fetch fails. 

I'm going to build a new image using the same code repo. It will created an image with a slightly different hash and i'll overwrite the current tag. Expect the tag to not be available for a few minutes during this.

**Comment by lukasz-bielinski** [comment]
i have to confirm
Mar 29 21:23:41 192.168.1.171 kubelet-wrapper[978]: run: openpgp: invalid signature: hash tag doesn't match

**Comment by bharrisau** [comment]
Can't remember the path. I just did

```
find / -name "*hyperkube*"  2>/dev/null
sudo rm [path to file]
```

**Comment by lukasz-bielinski** [comment]
@bharrisau i deleted key, but still see Mar 29 22:44:09 192.168.1.170 kubelet-wrapper[1845]: run: openpgp: invalid signature: hash tag doesn't match

**Comment by pbx0** [comment]
I can confirm the signature is still broken, we are working with the quay team to figure out what is going on.

@lukasz-bielinski You shouldn't need to force downloading the quay keys as that won't change (anytime soon at least). Once you have a key for a prefix, I believe rkt will stop automatically fetching a new signing key. This is akin to the trust-on-first-use principal that ssh uses. You can force downloading a new key for a given name prefix by explicitly trusting it: `rkt trust --prefix quay.io/coreos/hyperkube`

You can also manually delete keys in the trust store at `/etc/rkt/trustedkeys/prefix.d`

**Comment by bharrisau** [comment]
Just tried checking the sigs manually. Both `v1.2.0_coreos.1` and `v1.2.0_coreos.0` are signed with `799D33BC` which is the Quay ACI converter. But the signature is failing for the `.1` image.
I haven't been able to work out how to confirm that the Quay image I'm getting from `https://quay.io/c1/aci/quay.io/coreos/hyperkube/v1.2.0_coreos.1/aci/linux/amd64/` has the correct tag `fafaa6371fdd`. Maybe it hasn't changed over yet? None of the hashes I'm running on the file match the contents.

**Comment by bharrisau** [comment]
Signature validation error is:
```
gpg: Signature made Tue Mar 29 19:33:48 2016 UTC using RSA key ID 799D33BC
gpg: BAD signature from "Quay.io ACI Converter (ACI conversion signing key) <support@quay.io>" [unknown]
```
The signature timestamp looks correct - a couple of hours ago. I'll leave it to the CoreOS and Quay.io teams.

**Comment by pbx0** [comment]
Although we have not found the root cause of this, re-building and pushing eventually seemed to fix things. Closing this issue, please re-open it if you are seeing the same problem.
